//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListadoEstudiantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTAD
    {
        public int ID_FACULTAD { get; set; }
        public string Nombre_Facultad { get; set; }
        public string Director_Facultad { get; set; }
        public Nullable<decimal> Telefono_Facultad { get; set; }
        public string Correo_Facultad { get; set; }
        public string Localidad_Facultad { get; set; }
    }
}
