//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListadoEstudiantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int ID_HORARIOS { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
    }
}
